### PR TITLE
fix: Do not surface Practice Mode in config details in settings

### LINKED ISSUE #850: Config Screen / remove "Practice Mode"
Description:
Upon releasing v.5.3.0, we realized the words "Practice Mode" under the Current Configuration. Practice Mode is to be added later in the year and should've be displayed in this release.

To Do:
Remove the words "Practice Mode", revert to previous behavior.

### PR DESCRIPTION
**Pull request by achou11**
Fixes #850

Notes:
- Restores the originally surfaced config details i.e. in the case of the default config: the name of the default config + its version and its project key

Preview:

850-config-details-default

### CODE REVIEW

File: src/frontend/screens/Settings/ProjectConfig/ConfigDetails.tsx [hunk 1]
```diff
@@ -68,7 +68,7 @@ export const ConfigDetails = ({
           {isPracticeMode ? (
             <FormattedMessage {...m.practiceModeName} />
           ) : (
-            `${name} ${version && " v" + version}`
+            `${name}${version ? " " + formatDisplayedVersion(version) : ""}`
```
Comment (achou11) [inline src/frontend/screens/Settings/ProjectConfig/ConfigDetails.tsx:71]: unrelated change where i noticed that config versions may sometimes already be prefixed with `v`

**Review by ErikSin — APPROVED** [review]

**Comment by ErikSin** [comment]
Once its rebased you can merge it!
